src/Entity/FilterEvent.php
<?php

namespace App\Entity;

use App\Repository\FilterEventRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilterEventRepository::class)]
class FilterEvent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?Campus $campus = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $eventName = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $beginDate = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endDate = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isOrganizer = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isMember = null;

    #[ORM\Column]
    private ?bool $isNotMember = null;

    #[ORM\Column(nullable: true)]
    private ?bool $passed = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCampus(): ?object
    {
        return $this->campus;
    }

    public function setCampus(?object $campus): static
    {
        $this->campus = $campus;

        return $this;
    }

    public function getEventName(): ?string
    {
        return $this->eventName;
    }

    public function setEventName(?string $eventName): static
    {
        $this->eventName = $eventName;

        return $this;
    }

    public function getBeginDate(): ?\DateTimeImmutable
    {
        return $this->beginDate;
    }

    public function setBeginDate(?\DateTimeImmutable $beginDate): static
    {
        $this->beginDate = $beginDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeImmutable
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeImmutable $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function isOrganizer(): ?bool
    {
        return $this->isOrganizer;
    }

    public function setIsOrganizer(?bool $isOrganizer): static
    {
        $this->isOrganizer = $isOrganizer;

        return $this;
    }

    public function isMember(): ?bool
    {
        return $this->isMember;
    }

    public function setIsMember(?bool $isMember): static
    {
        $this->isMember = $isMember;

        return $this;
    }

    public function isNotMember(): ?bool
    {
        return $this->isNotMember;
    }

    public function setIsNotMember(bool $isNotMember): static
    {
        $this->isNotMember = $isNotMember;

        return $this;
    }

    public function isPassed(): ?bool
    {
        return $this->passed;
    }

    public function setPassed(?bool $passed): static
    {
        $this->passed = $passed;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\City;
use App\Entity\Event;
use App\Entity\Place;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'label' => 'Nom de l\'event :'
            ])
            ->add('beginDate', DateTimeType::class, [
                'widget' => 'single_text',
                'input' => 'datetime',
                'label' => 'Date et heure de l\'event :',
                'constraints' => [
                    new GreaterThanOrEqual([
                        'value' => new \DateTime('today'), // Date actuelle
                        'message' => 'La date ne peut pas être antérieure à aujourd\'hui.',
                    ]),
                ],
            ])
            ->add('duration', TimeType::class, [
                'input' => 'string',
                'widget' => 'single_text',
                'label' => 'Duree de l\'event :',
            ])
            ->add('limitDate', DateType::class, [
                'widget' => 'single_text',
                'input' => 'datetime',
                'label' => 'Date limite d\'inscription :',
                'constraints' => [
                    new GreaterThanOrEqual([
                        'value' => new \DateTime('today'), // Date actuelle
                        'message' => 'La date ne peut pas être antérieure à aujourd\'hui.',
                    ]),
                ],
            ])
            ->add('nbMaxInscription', null, [
                'label' => 'Nbre max d\'inscription :'
            ])
            ->add('infoEvent', null, [
                'label' => 'Description et infos :'
            ])
            ->add('campus')
            ->add('place', EntityType::class, [
                    'placeholder' => 'Choisir un lieu',
                    'class' => Place::class,
                    'choice_label' => 'name',
                    'label' => 'Lieu :'
                ]
            );

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\City;
use App\Entity\Event;
use App\Entity\FilterEvent;
use App\Entity\Place;
use App\Entity\State;
use App\Entity\User;
use App\Form\DataLocationType;
use App\Form\EventType;
use App\Form\FilterEventType;
use App\Repository\EventRepository;
use App\Repository\FilterEventRepository;
use App\Repository\StateRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use MobileDetectBundle\DeviceDetector\MobileDetectorInterface;

#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/create', name: 'create_event')]
    public function createEvent(Request $request, EntityManagerInterface $entityManager): Response
    {

        $event = new Event();
        $place = new Place();

        $eventForm = $this->createForm(EventType::class, $event)->handleRequest($request);
        $dataLocationForm = $this->createForm(DataLocationType::class, $place)->handleRequest($request);

        if ($eventForm->isSubmitted() && $eventForm->isValid()) {

            $placeName = $dataLocationForm->getData()->getName();
            $place = $entityManager->getRepository(Place::class)->findOneBy(['name' => $placeName]);
            $user = $entityManager->getRepository(User::class)->find($this->getUser()->getId());

            $state = null;
            if (isset($_POST['create'])) {
                $state = $entityManager->getRepository(State::class)->find(1);
            } elseif (isset($_POST['publish'])) {
                $state = $entityManager->getRepository(State::class)->find(2);
            }

            $event->setPlace($place);
            $event->setCampus($this->getUser()->getCampus());
            $event->setState($state);
            $event->addMember($user);
            $event->setOrganizer($this->getUser());

            $entityManager->persist($event);

            $entityManager->flush();
            $this->addFlash('success', 'Felicitation, vous venez de creer un Eni-Event!');
            return $this->redirectToRoute('event_showroom');
        }

        return $this->render('event/createEvent.html.twig', [
            'eventForm' => $eventForm->createView(),
            'locationForm' => $dataLocationForm->createView()
        ]);
    }

    #[Route('/edit/{id}', name: 'edit')]
    public function edit(Event $event, Request $request, EntityManagerInterface $entityManager): Response
    {
        if (isset($_POST['delete'])) {
            $entityManager->remove($event);
            $entityManager->flush();
            $this->addFlash('error', $event->getName() . ' ' . 'vient d\'etre supprime');
            return $this->redirectToRoute('event_showroom');
        }

        $place = new Place();
        $defaultCity = $entityManager->getRepository(City::class)->find($event->getPlace()->getCity()->getId());

        $defaultPlace = $entityManager->getRepository(Place::class)->find($event->getPlace()->getId());

        $eventForm = $this->createForm(EventType::class, $event)->handleRequest($request);
        $dataLocationForm = $this->createForm(DataLocationType::class, $place, ['default_city' => $defaultCity, 'default_place' => $defaultPlace])->handleRequest($request);

        if ($eventForm->isSubmitted() && $eventForm->isValid()) {
            $placeName = $dataLocationForm->getData()->getName();
            $place = $entityManager->getRepository(Place::class)->findOneBy(['name' => $placeName]);
            $user = $entityManager->getRepository(User::class)->find($this->getUser()->getId());

            $state = null;
            if (isset($_POST['create'])) {
                $state = $entityManager->getRepository(State::class)->find(1);
                $this->addFlash('success', 'Pour finaliser votre event vous devez le publier');
            } elseif (isset($_POST['publish'])) {
                $state = $entityManager->getRepository(State::class)->find(2);
                $this->addFlash('success', 'Vous venez de publier' . ' ' . $event->getName());
            }

            $event->setPlace($place);
            $event->setCampus($this->getUser()->getCampus());
            $event->setState($state);
            $event->addMember($user);
            $event->setOrganizer($this->getUser());

            $entityManager->flush();
            $this->addFlash('success', 'Modifications sur ' . ' ' . $event->getName() . ' ' . 'effectuees avec succès');
            return $this->redirectToRoute('event_showroom');
        }

        return $this->render('event/editEvent.html.twig', [
            'eventForm' => $eventForm->createView(),
            'locationForm' => $dataLocationForm->createView(),
            'event' => $event
        ]);
    }

    #[Route('/showroom', name: 'event_showroom')]
    public function eventShowroom(Request $request, EntityManagerInterface $entityManager, StateRepository $stateRepository, FilterEventRepository $filterEventRepository, MobileDetectorInterface $mobileDetector): Response
    {
        $filterEvent = new FilterEvent();

        $researchForm = $this->createForm(FilterEventType::class, $filterEvent);
        $eventRepo = $entityManager->getRepository(Event::class);
        $researchForm->handleRequest($request);

        $user = $this->getUser();
        $state = $stateRepository->find(3);
	
	if ($mobileDetector->isMobile()) {
		$filterEvent->setIsMember(true);
		$events = $filterEventRepository->findDynamic($user, $filterEvent, $state);
	}
	else if ($researchForm->isSubmitted() && $researchForm->isValid()) {
            $events = $filterEventRepository->findDynamic($user, $filterEvent, $state);
        } else {
		$events = $eventRepo->findBy([], [], 10);
        }

        return $this->render('event/eventShowroom.html.twig', [
            'form' => $researchForm->createView(),
	    'events' => $events
        ]);
    }

    #[Route('/publish/{id}', name: 'publish')]
    public function publish(Event $event, EntityManagerInterface $entityManager): Response
    {
        $openSate = $entityManager->getRepository(State::class)->find(2);
        $event->setState($openSate);
        $entityManager->flush();
        $this->addFlash('success', $event->getName() . ' ' . 'vient d\'etre ouvert aux inscritions');
        return $this->redirectToRoute('event_showroom');
    }

    #[Route('/register/{id}', name: 'register')]
    public function register(Event $event, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $event->addMember($user);
        $entityManager->flush();
        $this->addFlash('success', 'Vous venez de vous inscrire a l\'evenement:' . ' ' . $event->getName());
        return $this->redirectToRoute('event_showroom');
    }

    #[Route('/desist/{id}', name: 'desist')]
    public function desist(Event $event, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $event->removeMember($user);
        $entityManager->flush();
        $this->addFlash('success', 'Vous venez de vous desister de' . ' ' . $event->getName());
        return $this->redirectToRoute('event_showroom');
    }

    #[Route('/show/{id}', name: 'show')]
    public function show(Event $event): Response
    {
        return $this->render('event/eventShow.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/cancel/{id}', name: 'cancel')]
    public function cancel(Event $event, StateRepository $stateRepository, EntityManagerInterface $entityManager): Response
    {
        $closeState = $stateRepository->find(3);
        $event->setState($closeState);
        $entityManager->flush();

        return $this->redirectToRoute('cancelEvent');
    }

    #[Route('/deleteEvent/{id}', name: 'deleteEvent')]
    public function deleteEvent(Event $event, EntityManagerInterface $entityManager, EventRepository $eventRepository): Response
    {
        $entityManager->remove($event);
        $entityManager->flush();
        $events = $eventRepository->findAll();
        return $this->render('admin/cancel.html.twig', [
            'events' => $events,
        ]);
    }

    #[Route('/stash/{id}', name: 'stash')]
    public function stash(Event $event, Request $request, EntityManagerInterface $entityManager): Response
    {
        $closeSate = $entityManager->getRepository(State::class)->find(3);
        $motif = $request->get('motif');

        $event->setInfoEvent('Motif d\'annulation de l\'event:' . PHP_EOL . $motif);
        $event->setState($closeSate);
        $entityManager->flush();

        return $this->redirectToRoute('event_showroom');
    }


}

templates/event/cancelEvent.html.twig
{% extends 'base.html.twig' %}
    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="{{ asset('css/cancelEvent.css') }}">
    {% endblock %}
{% block title %}event.name{% endblock %}
{% block body %}
    <h1 class="m-2">{{ event.name }}</h1>
    <div class="form-container d-flex ">
        <div class="form-details d-flex flex-column m-1">
            <form method="post" action="{{ path('stash', {id :event.id}) }}">
                <div class="form-row">
                    <label for="">Nom de la sortie :</label>
                    <p>{{ event.name }}</p>
                </div>
                <div class="form-row">
                    <label for="">Date de la sortie :</label>
                    <p>{{ event.beginDate|date('d-m-Y') }}</p>
                </div>
                <div class="form-row">
                    <label for="">Campus :</label>
                    <p>{{ event.campus.name }}</p>
                </div>
                <div class="form-row">
                    <label for="">Lieu :</label>
                    <p>{{ event.place.name }}</p>
                </div>
                <div class="form-row">
                    <label for="motif">Motif :</label>
                    <textarea name="motif" id="" cols="30" rows="10" required></textarea>
                </div>
                <div class="buttons">
                    <button class="btn-primary" type="submit">Annuler l'event</button>
                    <a href="{{ path('event_showroom') }}">
                        <button class="btn-primary">Retour</button>
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/event/createEvent.html.twig
{% extends 'base.html.twig' %}
    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="{{ asset('css/createEvent.css') }}">
    {% endblock %}
{% block title %}Create-Event{% endblock %}
{% block body %}
    <h1 class="m-2">Creer un event</h1>
    {{ form_start(eventForm) }}
    <div class="form-container d-flex ">
        <div class="form-details d-flex flex-column m-1">
            <div class="form-row">
                {{ form_label(eventForm.name) }}
                {{ form_widget(eventForm.name) }}
            </div>
            {{ form_errors(eventForm.name) }}
            <div class="form-row">
                {{ form_label(eventForm.beginDate) }}
                {{ form_widget(eventForm.beginDate) }}
            </div>
            {{ form_errors(eventForm.beginDate) }}
            <div class="form-row">
                {{ form_label(eventForm.limitDate) }}
                {{ form_widget(eventForm.limitDate) }}
            </div>
            {{ form_errors(eventForm.limitDate) }}
            <div class="form-row">
                {{ form_label(eventForm.nbMaxInscription) }}
                {{ form_widget(eventForm.nbMaxInscription) }}
            </div>
            {{ form_errors(eventForm.nbMaxInscription) }}
            <div class="form-row">
                {{ form_label(eventForm.duration) }}
                {{ form_widget(eventForm.duration, {'type': 'time', 'format' : 'H:i'}) }}
            </div>
            {{ form_errors(eventForm.duration) }}
            <div class="form-row">
                {{ form_label(eventForm.infoEvent) }}
                {{ form_widget(eventForm.infoEvent) }}
            </div>
            {{ form_errors(eventForm.infoEvent) }}
        </div>
        <div class="form-location d-flex flex-column m-1">
            {% if app.user %}
                <div class="form-row">
                    <label>Campus :</label>
                    <p>{{ app.user.getCampus.getname }}</p>
                </div>
                {{ form_errors(eventForm.campus) }}
            {% endif %}
            <div class="form-row">
                {{ form_label(locationForm.city) }}
                <div>
                    {{ form_widget(locationForm.city) }}
                    <a class="btn-primary btn-add" href="{{ path('createCity.html.twig') }}">+</a>
                </div>
            </div>
            <div class="form-row">
                {{ form_label(locationForm.name) }}
                <div>
                    {{ form_widget(locationForm.name) }}
                    <a class="btn-primary btn-add" href="{{ path('createPlace') }}">+</a>
                </div>
            </div>
            <div class="form-row">
                {{ form_label(locationForm.postCode) }}
                {{ locationForm.postCode.vars.value }}
            </div>
            <div class="form-row">
                {{ form_label(locationForm.street) }}
                {{ locationForm.street.vars.value }}
            </div>
            <div class="form-row">
                {{ form_label(locationForm.latitude) }}
                {{ locationForm.latitude.vars.value }}
            </div>
            <div class="form-row">
                {{ form_label(locationForm.longitude) }}
                {{ locationForm.longitude.vars.value }}
            </div>
        </div>
    </div>
    <div class="buttons d-flex justify-content-center m-2">
        <button class="btn-primary" type="submit" name="create">Enregistrer</button>
        <a href="#">
            <button class="btn-primary" type="submit" name="publish">Publier</button>
        </a>
        <a class="btn-primary" href="{{ path('event_showroom') }}">Annuler
        </a>
    </div>
    {{ form_widget(eventForm._token) }}
    {{ form_widget(locationForm._token) }}
    {{ form_end(eventForm, {'render_rest': false}) }}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script defer src="{{ asset('js/dynamicSelect.js') }}"></script>
{% endblock %}

templates/event/editEvent.html.twig
{% extends 'base.html.twig' %}
    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="{{ asset('css/createEvent.css') }}">
        <link rel="stylesheet" href="{{ asset('css/editEvent.css') }}">
    {% endblock %}
{% block title %}Create-Event{% endblock %}
{% block body %}
    <h1 class="m-2">{{ event.name }}</h1>
    {{ form_start(eventForm) }}
    <div class="form-container d-flex ">
        <div class="form-details d-flex flex-column m-1">
            <div class="form-row">
                {{ form_label(eventForm.name) }}
                {{ form_widget(eventForm.name) }}
            </div>
            {{ form_errors(eventForm.name) }}
            <div class="form-row">
                {{ form_label(eventForm.beginDate) }}
                {{ form_widget(eventForm.beginDate) }}
            </div>
            {{ form_errors(eventForm.beginDate) }}
            <div class="form-row">
                {{ form_label(eventForm.limitDate) }}
                {{ form_widget(eventForm.limitDate) }}
            </div>
            {{ form_errors(eventForm.limitDate) }}
            <div class="form-row">
                {{ form_label(eventForm.nbMaxInscription) }}
                {{ form_widget(eventForm.nbMaxInscription) }}
            </div>
            {{ form_errors(eventForm.nbMaxInscription) }}
            <div class="form-row">
                {{ form_label(eventForm.duration) }}
                {{ form_widget(eventForm.duration, {'type': 'time', 'format' : 'H:i'}) }}
            </div>
            {{ form_errors(eventForm.duration) }}
            <div class="form-row">
                {{ form_label(eventForm.infoEvent) }}
                {{ form_widget(eventForm.infoEvent) }}
            </div>
            {{ form_errors(eventForm.infoEvent) }}
        </div>
        <div class="form-location d-flex flex-column m-1">
            {% if app.user %}
                <div class="form-row">
                    <label>Campus :</label>
                    <p>{{ app.user.getCampus.getname }}</p>
                </div>
                {{ form_errors(eventForm.campus) }}
            {% endif %}
            <div class="form-row">
                {{ form_label(locationForm.city) }}
                {{ form_widget(locationForm.city) }}
            </div>
            {{ form_errors(locationForm.city) }}
            <div class="form-row">
                {{ form_label(locationForm.name) }}
                <div>
                    {{ form_widget(locationForm.name) }}
                    <a href="#">
                        <button class="btn-primary btn-add">+</button>
                    </a>
                </div>
            </div>
            {{ form_errors(locationForm.name) }}
            <div class="form-row">
                {{ form_label(locationForm.street) }}
                {{ form_widget(locationForm.street) }}
            </div>
            {{ form_errors(locationForm.street) }}
            <div class="form-row">
                {{ form_label(locationForm.latitude) }}
                {{ form_widget(locationForm.latitude) }}
            </div>
            {{ form_errors(locationForm.latitude) }}
            <div class="form-row">
                {{ form_label(locationForm.longitude) }}
                {{ form_widget(locationForm.longitude) }}
            </div>
            {{ form_errors(locationForm.longitude) }}
        </div>
    </div>
    <div class="buttons d-flex justify-content-center m-2">
        <button class="btn-primary" type="submit" name="create">Enregistrer</button>
        <button class="btn-primary" type="submit" name="publish">Publier</button>
        <button class="btn-primary" type="submit" name="delete">Supprimer</button>
        <a class="btn-primary" href="{{ path('cancel',{id: event.id }) }}">Annuler
        </a>
    </div>
    {{ form_widget(eventForm._token) }}
    {{ form_end(eventForm, {'render_rest': false}) }}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script defer src="{{ asset('js/dynamicSelect.js') }}"></script>
{% endblock %}

templates/event/eventShowroom.html.twig
{% extends 'base.html.twig' %}

    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="{{ asset('css/eventShowroom.css') }}">
        <link rel="stylesheet" href="{{ asset('css/tablette.css') }}">
    {% endblock %}

{% block title %}Event-Showroom{% endblock %}
{% block body %}
    {% set today = "now"|date("d-m-Y") %}
    <div class="info">
        <div class="d-flex">
            <label class="mr-1 " for="user">Date :</label>
            <p>{{ today }}</p>
        </div>
        <div class="d-flex">
            <label class="mr-1 " for="user">Participant :</label>
            {% if app.user %}
                <p>{{ app.user.firstname }}</p>
            {% endif %}

        </div>
    </div>
    <h1 class="m-2">Évènements</h1>
    <form method="post" action="{{ path('event_showroom') }}">
        <div class="search-container">
            {{ form_start(form) }}
            <div class="part1">
                <div class="row">
                    {{ form_label(form.campus) }}
                    {{ form_widget(form.campus) }}
                </div>
                <div class="row">
                    {{ form_label(form.eventName) }}
                    {{ form_widget(form.eventName) }}
                </div>
                <div class="date">
                    <div class="row">
                        {{ form_label(form.beginDate) }}
                        {{ form_widget(form.beginDate) }}
                    </div>
                    <div class="row">
                        {{ form_label(form.endDate) }}
                        {{ form_widget(form.endDate) }}
                    </div>
                </div>
            </div>
            <div class="separator"></div>
            <div class="part2">
                <div class="row">
                    {{ form_widget(form.isOrganizer) }}
                    {{ form_label(form.isOrganizer) }}
                </div>
                <div class="row">
                    {{ form_widget(form.isMember) }}
                    {{ form_label(form.isMember) }}
                </div>
                <div class="row">
                    {{ form_widget(form.isNotMember) }}
                    {{ form_label(form.isNotMember) }}
                </div>
                <div class="row">
                    {{ form_widget(form.passed) }}
                    {{ form_label(form.passed) }}
                </div>
            </div>
            <div class="separator"></div>
            <div class="part3">
                <button class="btn-primary" type="submit">RECHERCHER</button>
            </div>
            {{ form_end(form) }}
        </div>
    </form>
    <div class="form-container">
        <table>
            <thead class="event-topbar">
            <tr>
                <th>Nom</th>
                <th>Date</th>
                <th class="noSmartphone">Clôture inscription</th>
                <th class="noSmartphone">Inscrits/Places</th>
                <th class="noSmartphone">État</th>
                <th class="noSmartphone">Inscrit</th>
                <th class="noSmartphone">Organisateur</th>
                <th class="noSmartphone">Action</th>
		<th class="smartphone">Lieu</th>

            </tr>
            </thead>
            <tbody>
            {% if events %}
                {% for event in events %}
                    {% set isMember = false %}
                    {% for member in event.members %}
                        {% if member == app.user %}
                            {% set isMember = true %}
                        {% endif %}
                    {% endfor %}
                    {% set isOrganizer = false %}
                    {% if app.user %}
                        {% if event.organizer.id == app.user.id %}
                            {% set isOrganizer = true %}
                        {% endif %}
                    {% endif %}
                    <tr class="event-item {{ cycle(['dark', 'light'], loop.index) }}">
                        <td><a class="snicky" href="{{ path('show',{id: event.id }) }}">{{ event.name }}</a></td>
                        <td>{{ event.beginDate | date("m/d/Y") }}</td>
                        <td class="noSmartphone">{{ event.limitDate | date("m/d/Y") }}</td>
                        <td class="noSmartphone">{{ event.getNbrOfMembers }}/{{ event.nbMaxInscription }}</td>
                        <td class="noSmartphone">{{ event.state.label }}</td>
                        {% if isMember %}
                            <td class="isMember noSmartphone">X</td>
                        {% else %}
                            <td class="isMember noSmartphone"></td>
                        {% endif %}
                        <td class="isOrganizer noSmartphone"><a
                                    href="{{ path('showProfil',{id: event.organizer.id }) }}">{{ event.organizer.firstname }} {{ event.organizer.name | slice(0, 1) | capitalize }}</a>
                        </td>
                        {% if isMember and not isOrganizer and event.limitDate | date("m/d/Y")|date('U') > today | date("m/d/Y")|date('U') %}
                            <td class="noSmartphone"><a href="{{ path('show',{id: event.id }) }}">Afficher</a> / <a
                                        href="{{ path('desist',{id: event.id }) }}">Se desister</a></td>
                        {% elseif not isMember and not isOrganizer and event.state.label == 'Ouvert' and event.limitDate | date("m/d/Y")|date('U') > today | date("m/d/Y")|date('U') and  event.getNbrOfMembers < event.nbMaxInscription %}
                            <td class="noSmartphone"><a href="{{ path('show',{id: event.id }) }}">Afficher</a> / <a
                                        href="{{ path('register',{id: event.id }) }}">S'inscrire</a></td>
                        {% elseif isOrganizer and event.state.label == 'En cours' %}
                            <td class="noSmartphone"><a href="{{ path('edit',{id: event.id }) }}">Modifier</a> / <a
                                        href="{{ path('publish',{id: event.id }) }}">Publier</a></td>
                        {% elseif isOrganizer and event.state.label == 'En creation' %}
                            <td class="noSmartphone"><a href="{{ path('edit',{id: event.id }) }}">Modifier</a></td>
                        {% elseif event.limitDate | date("m/d/Y")|date('U') <= today | date("m/d/Y")|date('U') or event.state.label == 'Ferme' %}
                            <td class="noSmartphone"><a href="{{ path('show',{id: event.id }) }}">Afficher</a></td>
                        {% elseif event.state.label == 'Ouvert' and isOrganizer %}
                            <td class="noSmartphone"><a href="{{ path('show',{id: event.id }) }}">Afficher</a> / <a
                                        href="{{ path('cancel',{id: event.id }) }}">Annuler</a></td>
                        {% else %}
                            <td></td>
                        {% endif %}
			<td class="smartphone">{{ event.campus }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
    <div class="button m-2">
        <a href="{{ path('create_event') }}">
            <button class="btn-primary">Créer un évènement</button>
        </a>
    </div>
    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
{% endblock %}